import java.net.URISyntaxException;
import java.util.Scanner;

import sam.jersey.app.App;
import sam.jersey.app.Server;
import sam.jersey.utils.ANSI;
import sam.jersey.utils.Utils;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
    public static void main(String[] args) throws URISyntaxException {
    	Server server = null;
		try {
			server = new Server(true);
			waitForExit(new String[]{"/"});
		} finally {
			if(server != null)
				server.shutdownNow();
		}
	}
    
	private static void waitForExit(String[]... suburls) {
		if(Utils.isEmpty(suburls))
			System.out.println(ANSI.yellow("application started at: ")+App.BASE_URI+"\n"+ANSI.red("type --exit to exit...."));
		else {
			StringBuilder sb = ANSI.cyan("Application started.\nTry out one of these URIs:", new StringBuilder()).append('\n');
			String base = App.BASE_URI;
			if(base.charAt(base.length() - 1) != '/')
				base = base.concat("/");

			for (String[] s0 : suburls) {
				for (String s : s0) {
					sb.append("  ");
					ANSI.yellow(App.BASE_URI, sb);
					ANSI.yellow(s.charAt(0) == '/' ? s.substring(1) : s, sb);
					sb.append('\n');	
				}
				sb.append('\n');
			}

			sb.append('\n');
			ANSI.red("type --exit to exit....", sb);
			
			System.out.println(sb);
			sb = null;
		}

		@SuppressWarnings("resource")
		Scanner sc = new Scanner(System.in);
		while(true) {
			if(sc.nextLine().trim().equalsIgnoreCase("--exit"))
				break;
		}
	}

	private Main() {}
    
}
