import java.net.URI;
import java.net.URISyntaxException;
import java.util.Scanner;

import org.glassfish.grizzly.http.server.HttpServer;
import org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory;
import org.glassfish.jersey.server.ResourceConfig;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
    public static void main(String[] args) throws URISyntaxException {
		HttpServer server = null;
		try {
			ResourceConfig config = new ResourceConfig(
					ClipboardRest.class,
					ClipboardDataProvider.ClipboardDataReader.class,
					ClipboardDataProvider.ClipboardDataWriter.class,
					ClipboardListWriter.class
					);
			config.register(new StoreBinder());
			server = GrizzlyHttpServerFactory.createHttpServer(new URI("http://localhost:8080/"), config, true);
			waitForExit();
		} finally {
			if(server != null)
				server.shutdownNow();
		}
	}
    
    private static void waitForExit() {
		System.out.println("type --exit to exit....");
		
		@SuppressWarnings("resource")
		Scanner sc = new Scanner(System.in);
		while(true) {
			if(sc.nextLine().trim().equalsIgnoreCase("--exit"))
				break;
		}
	}
    
    
}
