import java.net.URI;
import java.net.URISyntaxException;
import java.util.HashSet;
import java.util.Scanner;
import java.util.Set;

import javax.json.stream.JsonGenerator;
import javax.ws.rs.core.Application;

import org.glassfish.grizzly.http.server.HttpServer;
import org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory;
import org.glassfish.jersey.jsonp.JsonProcessingFeature;
import org.glassfish.jersey.server.ResourceConfig;

import sam.grizzly.jersey.Hello;
import sam.grizzly.jersey.Obj;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
    public static void main(String[] args) throws URISyntaxException {
    	System.setProperty("java.util.logging.config.file","logging.properties");
    	
		HttpServer server = null;
		try {
			ResourceConfig config = new ResourceConfig(Hello.class, Obj.class);
			config.property(JsonGenerator.PRETTY_PRINTING, true);
			
			server = GrizzlyHttpServerFactory.createHttpServer(new URI("http://localhost:8080/"), config, true);
			
			waitForExit();
		} finally {
			if(server != null)
				server.shutdownNow();
		}
	}
    
    private static void waitForExit() {
		System.out.println("type --exit to exit....");
		
		@SuppressWarnings("resource")
		Scanner sc = new Scanner(System.in);
		while(true) {
			if(sc.nextLine().trim().equalsIgnoreCase("--exit"))
				break;
		}
	}
    
    
}
