import java.net.URI;
import java.net.URISyntaxException;
import java.util.Scanner;

import org.glassfish.grizzly.http.server.HttpServer;
import org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpServerFactory;

import sam.jersey.app.App;
import sam.jersey.utils.ANSI;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
    public static void main(String[] args) throws URISyntaxException {
		HttpServer server = null;
		try {
			server = GrizzlyHttpServerFactory.createHttpServer(new URI(App.BASE_URI), new App(), true);
			
			System.out.println(ANSI.cyan("Application started.\nTry out one of these URIs:"));
            for (final String path : new String[]{
            		"people/1234", 
            		"people/1234?select=familyName,givenName",
                    "people/1234?select=region,addresses.region",
                    "people/1234?select=familyName,givenName,addresses.phoneNumber.number"}) {
                System.out.println(ANSI.yellow(App.BASE_URI.concat(path)));
            }
			waitForExit();
		} finally {
			if(server != null)
				server.shutdownNow();
		}
	}
    
    private static void waitForExit() {
		System.out.println(ANSI.red("type --exit to exit...."));
		
		@SuppressWarnings("resource")
		Scanner sc = new Scanner(System.in);
		while(true) {
			if(sc.nextLine().trim().equalsIgnoreCase("--exit"))
				break;
		}
	}
    
    private Main() {}
    
    
}
